**_Copyright Notice_**

This notebook is available for educational purposes. You may not use or distribute this notebook for commercial purposes. You may make copies of this notebook and use or distribute it for educational purposes as long as you cite the author as the source of the notebook.

Jaeyoung Chun | School of Applied Artificial Intelligence | Handong Global University

# Feature Engineering

In [1]:
import pandas as pd
import os

## Load Match/Rank Data

In [2]:
df_merge_match_rank = pd.read_parquet("./intermediate/match_rank.parquet")

In [3]:
df_merge_match_rank

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral,rank_home,total_points_home,rank_change_home,rank_away,total_points_away,rank_change_away
0,2018-08-18,Andorra,United Arab Emirates,0,0,Friendly,Grödig,Austria,True,130,1120.00,0,77,1312.00,0
1,2018-08-18,Grenada,Jamaica,1,5,Friendly,St. George's,Grenada,False,168,980.00,0,54,1400.00,0
2,2018-08-18,Guatemala,Cuba,1,0,Friendly,Quetzaltenango,Guatemala,False,146,1064.00,0,181,940.00,0
3,2018-08-20,Barbados,Jamaica,2,2,Friendly,Bridgetown,Barbados,False,160,1005.00,0,54,1400.00,0
4,2018-08-26,Barbados,Cuba,0,0,Friendly,Bridgetown,Barbados,False,160,1005.00,0,181,940.00,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3402,2022-09-27,Norway,Serbia,0,2,UEFA Nations League,Oslo,Norway,False,36,1488.57,0,25,1549.53,0
3403,2022-09-27,Sweden,Slovenia,1,1,UEFA Nations League,Stockholm,Sweden,False,20,1563.44,0,65,1372.48,0
3404,2022-09-27,Kosovo,Cyprus,5,1,UEFA Nations League,Pristina,Kosovo,False,106,1183.90,0,108,1180.52,1
3405,2022-09-27,Greece,Northern Ireland,3,1,UEFA Nations League,Athens,Greece,False,49,1441.45,1,58,1399.10,0
3406,2022-09-30,Fiji,Solomon Islands,1,0,MSG Prime Minister's Cup,Luganville,Vanuatu,True,163,993.37,0,137,1092.56,0

## Split into Home and Away Team

### Extract and Create Home Team DataFrame

In [4]:
# Build a unified long-format table: each match appears twice — once per team
df_home = df_merge_match_rank[
    ['date','home_team','away_team','home_score','away_score', 'rank_home', 'rank_away', 'total_points_home', 'neutral', 'tournament']
].copy()

In [5]:
df_home

,date,home_team,away_team,home_score,away_score,rank_home,rank_away,total_points_home,neutral,tournament
0,2018-08-18,Andorra,United Arab Emirates,0,0,130,77,1120.00,True,Friendly
1,2018-08-18,Grenada,Jamaica,1,5,168,54,980.00,False,Friendly
2,2018-08-18,Guatemala,Cuba,1,0,146,181,1064.00,False,Friendly
3,2018-08-20,Barbados,Jamaica,2,2,160,54,1005.00,False,Friendly
4,2018-08-26,Barbados,Cuba,0,0,160,181,1005.00,False,Friendly
...,...,...,...,...,...,...,...,...,...,...
3402,2022-09-27,Norway,Serbia,0,2,36,25,1488.57,False,UEFA Nations League
3403,2022-09-27,Sweden,Slovenia,1,1,20,65,1563.44,False,UEFA Nations League
3404,2022-09-27,Kosovo,Cyprus,5,1,106,108,1183.90,False,UEFA Nations League
3405,2022-09-27,Greece,Northern Ireland,3,1,49,58,1441.45,False,UEFA Nations League
3406,2022-09-30,Fiji,Solomon Islands,1,0,163,137,993.37,True,MSG Prime Minister's Cup

In [6]:
# label all the rows as 1 indicating home team
df_home['is_home'] = 1

In [7]:
df_home

,date,home_team,away_team,home_score,away_score,rank_home,rank_away,total_points_home,neutral,tournament,is_home
0,2018-08-18,Andorra,United Arab Emirates,0,0,130,77,1120.00,True,Friendly,1
1,2018-08-18,Grenada,Jamaica,1,5,168,54,980.00,False,Friendly,1
2,2018-08-18,Guatemala,Cuba,1,0,146,181,1064.00,False,Friendly,1
3,2018-08-20,Barbados,Jamaica,2,2,160,54,1005.00,False,Friendly,1
4,2018-08-26,Barbados,Cuba,0,0,160,181,1005.00,False,Friendly,1
...,...,...,...,...,...,...,...,...,...,...,...
3402,2022-09-27,Norway,Serbia,0,2,36,25,1488.57,False,UEFA Nations League,1
3403,2022-09-27,Sweden,Slovenia,1,1,20,65,1563.44,False,UEFA Nations League,1
3404,2022-09-27,Kosovo,Cyprus,5,1,106,108,1183.90,False,UEFA Nations League,1
3405,2022-09-27,Greece,Northern Ireland,3,1,49,58,1441.45,False,UEFA Nations League,1
3406,2022-09-30,Fiji,Solomon Islands,1,0,163,137,993.37,True,MSG Prime Minister's Cup,1

### Extract and Create Away Team DataFrame

In [8]:
df_away = df_merge_match_rank[[
    'date', 'away_team', 'home_team', 'away_score', 'home_score', 'rank_away', 'rank_home', 'total_points_away', 'neutral', 'tournament']
].copy()

In [9]:
df_away

,date,away_team,home_team,away_score,home_score,rank_away,rank_home,total_points_away,neutral,tournament
0,2018-08-18,United Arab Emirates,Andorra,0,0,77,130,1312.00,True,Friendly
1,2018-08-18,Jamaica,Grenada,5,1,54,168,1400.00,False,Friendly
2,2018-08-18,Cuba,Guatemala,0,1,181,146,940.00,False,Friendly
3,2018-08-20,Jamaica,Barbados,2,2,54,160,1400.00,False,Friendly
4,2018-08-26,Cuba,Barbados,0,0,181,160,940.00,False,Friendly
...,...,...,...,...,...,...,...,...,...,...
3402,2022-09-27,Serbia,Norway,2,0,25,36,1549.53,False,UEFA Nations League
3403,2022-09-27,Slovenia,Sweden,1,1,65,20,1372.48,False,UEFA Nations League
3404,2022-09-27,Cyprus,Kosovo,1,5,108,106,1180.52,False,UEFA Nations League
3405,2022-09-27,Northern Ireland,Greece,1,3,58,49,1399.10,False,UEFA Nations League
3406,2022-09-30,Solomon Islands,Fiji,0,1,137,163,1092.56,True,MSG Prime Minister's Cup

In [10]:
# label all the rows as 1 indicating home team
df_away['is_home'] = 0

In [11]:
df_away

,date,away_team,home_team,away_score,home_score,rank_away,rank_home,total_points_away,neutral,tournament,is_home
0,2018-08-18,United Arab Emirates,Andorra,0,0,77,130,1312.00,True,Friendly,0
1,2018-08-18,Jamaica,Grenada,5,1,54,168,1400.00,False,Friendly,0
2,2018-08-18,Cuba,Guatemala,0,1,181,146,940.00,False,Friendly,0
3,2018-08-20,Jamaica,Barbados,2,2,54,160,1400.00,False,Friendly,0
4,2018-08-26,Cuba,Barbados,0,0,181,160,940.00,False,Friendly,0
...,...,...,...,...,...,...,...,...,...,...,...
3402,2022-09-27,Serbia,Norway,2,0,25,36,1549.53,False,UEFA Nations League,0
3403,2022-09-27,Slovenia,Sweden,1,1,65,20,1372.48,False,UEFA Nations League,0
3404,2022-09-27,Cyprus,Kosovo,1,5,108,106,1180.52,False,UEFA Nations League,0
3405,2022-09-27,Northern Ireland,Greece,1,3,58,49,1399.10,False,UEFA Nations League,0
3406,2022-09-30,Solomon Islands,Fiji,0,1,137,163,1092.56,True,MSG Prime Minister's Cup,0

### Rename Columns

In [12]:
col_names = ['date', 'team', 'opponent', 'goals_scored', 'goals_conceded', 'team_rank', 'opp_rank', 'team_points', 'neutral', 'tournament', "is_home"]

In [13]:
df_home.columns = col_names

In [14]:
df_away.columns = col_names

## Concatenate

In [15]:
df_concat = pd.concat([df_home, df_away]).sort_values('date')

In [16]:
df_concat

,date,team,opponent,goals_scored,goals_conceded,team_rank,opp_rank,team_points,neutral,tournament,is_home
0,2018-08-18,Andorra,United Arab Emirates,0,0,130,77,1120.00,True,Friendly,1
1,2018-08-18,Grenada,Jamaica,1,5,168,54,980.00,False,Friendly,1
2,2018-08-18,Guatemala,Cuba,1,0,146,181,1064.00,False,Friendly,1
2,2018-08-18,Cuba,Guatemala,0,1,181,146,940.00,False,Friendly,0
1,2018-08-18,Jamaica,Grenada,5,1,54,168,1400.00,False,Friendly,0
...,...,...,...,...,...,...,...,...,...,...,...
3388,2022-09-27,Mexico,Colombia,2,3,12,17,1649.57,True,Friendly,1
3405,2022-09-27,Northern Ireland,Greece,1,3,58,49,1399.10,False,UEFA Nations League,0
3404,2022-09-27,Cyprus,Kosovo,1,5,108,106,1180.52,False,UEFA Nations League,0
3406,2022-09-30,Fiji,Solomon Islands,1,0,163,137,993.37,True,MSG Prime Minister's Cup,1
3406,2022-09-30,Solomon Islands,Fiji,0,1,137,163,1092.56,True,MSG Prime Minister's Cup,0

In [17]:
df_concat.head(20)

,date,team,opponent,goals_scored,goals_conceded,team_rank,opp_rank,team_points,neutral,tournament,is_home
0,2018-08-18,Andorra,United Arab Emirates,0,0,130,77,1120.0,True,Friendly,1
1,2018-08-18,Grenada,Jamaica,1,5,168,54,980.0,False,Friendly,1
2,2018-08-18,Guatemala,Cuba,1,0,146,181,1064.0,False,Friendly,1
2,2018-08-18,Cuba,Guatemala,0,1,181,146,940.0,False,Friendly,0
1,2018-08-18,Jamaica,Grenada,5,1,54,168,1400.0,False,Friendly,0
0,2018-08-18,United Arab Emirates,Andorra,0,0,77,130,1312.0,True,Friendly,0
3,2018-08-20,Barbados,Jamaica,2,2,160,54,1005.0,False,Friendly,1
3,2018-08-20,Jamaica,Barbados,2,2,54,160,1400.0,False,Friendly,0
4,2018-08-26,Barbados,Cuba,0,0,160,181,1005.0,False,Friendly,1
4,2018-08-26,Cuba,Barbados,0,0,181,160,940.0,False,Friendly,0
6,2018-08-29,Cuba,Barbados,2,0,181,160,940.0,False,Friendly,0
7,2018-08-29,Solomon Islands,Macau,4,1,143,185,1072.0,False,Friendly,0
5,2018-08-29,Sri Lanka,Bangladesh,1,0,200,194,888.0,False,Friendly,0
7,2018-08-29,Macau,Solomon Islands,1,4,185,143,924.0,False,Friendly,1
6,2018-08-29,Barbados,Cuba,0,2,160,181,1005.0,False,Friendly,1
5,2018-08-29,Bangladesh,Sri Lanka,0,1,194,200,904.0,False,Friendly,1
8,2018-09-02,Burundi,Ethiopia,1,1,148,151,1056.0,False,Friendly,0
9,2018-09-02,Macau,Mongolia,1,4,185,186,924.0,False,EAFF Championship,0
9,2018-09-02,Mongolia,Macau,4,1,186,185,920.0,False,EAFF Championship,1
8,2018-09-02,Ethiopia,Burundi,1,1,151,148,1044.0,False,Friendly,1

In [18]:
df_concat.loc[1348]

,date,team,opponent,goals_scored,goals_conceded,team_rank,opp_rank,team_points,neutral,tournament,is_home
1348,2019-12-18,Japan,South Korea,0,1,28,41,1500.0,False,EAFF Championship,0
1348,2019-12-18,South Korea,Japan,1,0,41,28,1459.0,False,EAFF Championship,1

## Rolling Stats per Team

Purpose: For each match, compute a team's historical performance stats using only data from before that match (no data leakage), then return those as new columns.

Iterates per team — for each team, it isolates and time-sorts that team's matches.

Two types of lookback, both with shift(1) to exclude the current game:

- Expanding (full cycle): gs.shift(1).expanding().mean() — average over all prior matches since Aug 2018. Columns: goals_avg, goals_suf_avg, rank_avg, points_avg
- Rolling (last 5 games): gs.shift(1).rolling(5, min_periods=1).mean() — average over the most recent 5 matches. Columns: goals_avg_l, goals_suf_avg_l, rank_avg_l, points_avg_l

### Generate

In [19]:
def rolling_team_stats(
    df, team_col, goals_scored_col, goals_conceded_col,
    rank_col, points_col, window=5
):
    # compute per-team rolling stats
    # - full cycle
    # - last `n` games (window)

    rows = []
    teams = df[team_col].unique()

    for team in teams:

        mask = df[team_col] == team
        team_df = df[mask].sort_values('date').copy()

        gs = team_df[goals_scored_col]
        gc = team_df[goals_conceded_col]
        rk = team_df[rank_col]
        pts = team_df[points_col]

        # expanding (full cycle) — shift(1) so we never use the current game's data
        team_df['goals_avg'] = gs.shift(1).expanding().mean()
        team_df['goals_suf_avg'] = gc.shift(1).expanding().mean()
        team_df['rank_avg'] = rk.shift(1).expanding().mean()
        team_df['points_avg']  = pts.shift(1).expanding().mean()

        # rolling (last `n` games)
        team_df['goals_avg_lastn'] = gs.shift(1).rolling(window, min_periods=1).mean()
        team_df['goals_suf_avg_lastn'] = gc.shift(1).rolling(window, min_periods=1).mean()
        team_df['rank_avg_lastn'] = rk.shift(1).rolling(window, min_periods=1).mean()
        team_df['points_avg_lastn'] = pts.shift(1).rolling(window, min_periods=1).mean()

        rows.append(team_df)

    result = pd.concat(rows).sort_index()
    
    return result

In [20]:
df_stats = rolling_team_stats(
    df_concat,
    team_col='team',
    goals_scored_col='goals_scored',
    goals_conceded_col='goals_conceded',
    rank_col='opp_rank',
    points_col='team_points'
)

In [21]:
df_stats

,date,team,opponent,goals_scored,goals_conceded,team_rank,opp_rank,team_points,neutral,tournament,is_home,goals_avg,goals_suf_avg,rank_avg,points_avg,goals_avg_lastn,goals_suf_avg_lastn,rank_avg_lastn,points_avg_lastn
0,2018-08-18,Andorra,United Arab Emirates,0,0,130,77,1120.00,True,Friendly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,2018-08-18,United Arab Emirates,Andorra,0,0,77,130,1312.00,True,Friendly,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2018-08-18,Grenada,Jamaica,1,5,168,54,980.00,False,Friendly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2018-08-18,Jamaica,Grenada,5,1,54,168,1400.00,False,Friendly,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2018-08-18,Cuba,Guatemala,0,1,181,146,940.00,False,Friendly,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3404,2022-09-27,Kosovo,Cyprus,5,1,106,108,1183.90,False,UEFA Nations League,1,1.434783,1.304348,77.456522,1150.793913,1.2,1.4,65.4,1175.900
3405,2022-09-27,Northern Ireland,Greece,1,3,58,49,1399.10,False,UEFA Nations League,0,1.023256,1.279070,57.906977,1454.282093,1.2,1.4,95.6,1418.660
3405,2022-09-27,Greece,Northern Ireland,3,1,49,58,1441.45,False,UEFA Nations League,1,1.090909,0.909091,73.931818,1419.390682,1.4,0.2,96.2,1425.434
3406,2022-09-30,Fiji,Solomon Islands,1,0,163,137,993.37,True,MSG Prime Minister's Cup,1,1.666667,1.222222,156.166667,991.177222,1.2,1.2,157.4,994.530
3406,2022-09-30,Solomon Islands,Fiji,0,1,137,163,1092.56,True,MSG Prime Minister's Cup,0,2.785714,1.857143,163.642857,1077.445714,1.8,2.0,151.6,1080.692

In [22]:
df_stats[ (df_stats["date"] == "2018-09-07") & (df_stats["team"] == "South Korea") ]

,date,team,opponent,goals_scored,goals_conceded,team_rank,opp_rank,team_points,neutral,tournament,is_home,goals_avg,goals_suf_avg,rank_avg,points_avg,goals_avg_lastn,goals_suf_avg_lastn,rank_avg_lastn,points_avg_lastn
45,2018-09-07,South Korea,Costa Rica,2,0,57,32,1387.0,False,Friendly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
df_stats[ df_stats["team"] == "South Korea" ]

,date,team,opponent,goals_scored,goals_conceded,team_rank,opp_rank,team_points,neutral,tournament,is_home,goals_avg,goals_suf_avg,rank_avg,points_avg,goals_avg_lastn,goals_suf_avg_lastn,rank_avg_lastn,points_avg_lastn
45,2018-09-07,South Korea,Costa Rica,2,0,57,32,1387.00,False,Friendly,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
122,2018-09-11,South Korea,Chile,0,0,57,12,1387.00,False,Friendly,1,2.000000,0.000000,32.000000,1387.000000,2.000000,0.000000,32.000000,1387.000000
169,2018-10-12,South Korea,Uruguay,2,1,55,5,1395.00,False,Friendly,1,1.000000,0.000000,22.000000,1387.000000,1.000000,0.000000,22.000000,1387.000000
246,2018-10-16,South Korea,Panama,2,2,55,70,1395.00,False,Friendly,1,1.333333,0.333333,16.333333,1389.666667,1.333333,0.333333,16.333333,1389.666667
332,2018-11-17,South Korea,Australia,1,1,53,42,1401.00,False,Friendly,0,1.500000,0.750000,29.750000,1391.000000,1.500000,0.750000,29.750000,1391.000000
393,2018-11-20,South Korea,Uzbekistan,4,0,53,94,1401.00,True,Friendly,1,1.400000,0.800000,32.200000,1393.000000,1.400000,0.800000,32.200000,1393.000000
430,2018-12-31,South Korea,Saudi Arabia,0,0,53,69,1405.00,True,Friendly,1,1.833333,0.666667,42.500000,1394.333333,1.800000,0.800000,44.600000,1395.800000
438,2019-01-07,South Korea,Philippines,1,0,53,116,1405.00,True,AFC Asian Cup,1,1.571429,0.571429,46.285714,1395.857143,1.800000,0.800000,56.000000,1399.400000
470,2019-01-22,South Korea,Bahrain,2,1,53,113,1405.00,True,AFC Asian Cup,1,1.500000,0.500000,55.000000,1397.000000,1.600000,0.600000,78.200000,1401.400000
473,2019-01-25,South Korea,Qatar,0,1,53,93,1405.00,True,AFC Asian Cup,1,1.555556,0.555556,61.444444,1397.888889,1.600000,0.400000,86.800000,1403.400000
509,2019-03-22,South Korea,Bolivia,1,0,38,60,1451.00,False,Friendly,1,1.400000,0.600000,64.600000,1398.600000,1.400000,0.400000,97.000000,1404.200000
585,2019-03-26,South Korea,Colombia,2,1,38,12,1451.00,False,Friendly,1,1.363636,0.545455,64.181818,1403.363636,0.800000,0.400000,90.200000,1414.200000
663,2019-06-07,South Korea,Australia,1,0,37,41,1462.00,False,Friendly,1,1.416667,0.583333,59.833333,1407.333333,1.200000,0.600000,78.800000,1423.400000
723,2019-06-11,South Korea,Iran,1,1,37,21,1462.00,False,Friendly,1,1.384615,0.538462,58.384615,1411.538462,1.200000,0.600000,63.800000,1434.800000
893,2019-09-05,South Korea,Georgia,2,2,37,94,1467.00,True,Friendly,1,1.357143,0.571429,55.714286,1415.142857,1.000000,0.600000,45.400000,1446.200000
1021,2019-09-10,South Korea,Turkmenistan,2,0,37,132,1467.00,False,FIFA World Cup qualification,0,1.400000,0.666667,58.266667,1418.600000,1.400000,0.800000,45.600000,1458.600000
1075,2019-10-10,South Korea,Sri Lanka,8,0,37,202,1470.00,False,FIFA World Cup qualification,1,1.437500,0.625000,62.875000,1421.625000,1.600000,0.800000,60.000000,1461.800000
1219,2019-11-14,South Korea,Lebanon,0,0,39,91,1466.00,False,FIFA World Cup qualification,0,1.823529,0.588235,71.058824,1424.470588,2.800000,0.600000,98.000000,1465.600000
1312,2019-11-19,South Korea,Brazil,0,3,39,3,1466.00,True,Friendly,0,1.722222,0.555556,72.166667,1426.777778,2.600000,0.600000,108.000000,1466.400000
1346,2019-12-11,South Korea,Hong Kong,2,0,41,139,1459.00,False,EAFF Championship,1,1.631579,0.684211,68.526316,1428.842105,2.400000,1.000000,104.400000,1467.200000
1348,2019-12-18,South Korea,Japan,1,0,41,28,1459.00,False,EAFF Championship,1,1.650000,0.650000,72.050000,1430.350000,2.400000,0.600000,113.400000,1465.600000
1597,2020-11-14,South Korea,Mexico,2,3,38,11,1464.00,True,Friendly,0,1.619048,0.619048,69.952381,1431.714286,2.200000,0.600000,92.600000,1464.000000
1647,2020-11-17,South Korea,Qatar,2,1,38,57,1464.00,True,Friendly,1,1.636364,0.727273,67.272727,1433.181818,1.000000,1.200000,54.400000,1462.800000
1728,2021-03-25,South Korea,Japan,0,3,38,27,1465.00,False,Friendly,0,1.652174,0.739130,66.826087,1434.521739,1.400000,1.400000,47.600000,1462.400000
1951,2021-06-05,South Korea,Turkmenistan,5,0,39,130,1460.25,False,FIFA World Cup qualification,1,1.583333,0.833333,65.166667,1435.791667,1.400000,1.400000,52.400000,1462.200000
2013,2021-06-09,South Korea,Sri Lanka,5,0,39,204,1460.25,False,FIFA World Cup qualification,1,1.720000,0.800000,67.760000,1436.770000,2.000000,1.400000,50.600000,1462.450000
2039,2021-06-13,South Korea,Lebanon,2,1,39,93,1460.25,False,FIFA World Cup qualification,1,1.846154,0.769231,73.000000,1437.673077,2.800000,1.400000,85.800000,1462.700000
2233,2021-09-02,South Korea,Iraq,0,0,36,70,1474.96,False,FIFA World Cup qualification,1,1.851852,0.777778,73.740741,1438.509259,2.800000,1.000000,102.200000,1461.950000
2326,2021-09-07,South Korea,Lebanon,1,0,36,98,1474.96,False,FIFA World Cup qualification,1,1.785714,0.750000,73.607143,1439.811071,2.400000,0.800000,104.800000,1464.142000
2380,2021-10-07,South Korea,Syria,2,1,36,81,1479.41,False,FIFA World Cup qualification,1,1.758621,0.724138,74.448276,1441.023103,2.600000,0.200000,119.000000,1466.134000
2477,2021-10-12,South Korea,Iran,1,1,36,22,1479.41,False,FIFA World Cup qualification,0,1.766667,0.733333,74.666667,1442.302667,2.000000,0.400000,109.200000,1469.966000
2537,2021-11-11,South Korea,United Arab Emirates,1,0,35,71,1489.10,False,FIFA World Cup qualification,1,1.741935,0.741935,72.967742,1443.499677,1.200000,0.600000,72.800000,1473.798000
2635,2021-11-16,South Korea,Iraq,3,0,35,72,1489.10,True,FIFA World Cup qualification,0,1.718750,0.718750,72.906250,1444.924687,1.000000,0.400000,68.400000,1479.568000
2745,2022-01-15,South Korea,Iceland,5,1,33,62,1507.24,True,Friendly,1,1.757576,0.696970,72.878788,1446.263333,1.600000,0.400000,68.800000,1482.396000
2761,2022-01-20,South Korea,Moldova,4,0,33,181,1507.24,True,Friendly,1,1.852941,0.705882,72.558824,1448.056765,2.400000,0.600000,61.600000,1488.852000
2781,2022-01-27,South Korea,Lebanon,1,0,33,95,1507.24,False,FIFA World Cup qualification,0,1.914286,0.685714,75.657143,1449.747714,2.800000,0.400000,81.600000,1494.418000
2811,2022-02-01,South Korea,Syria,2,0,33,86,1507.24,True,FIFA World Cup qualification,0,1.888889,0.666667,76.194444,1451.344722,2.800000,0.200000,96.200000,1499.984000
2851,2022-03-24,South Korea,Iran,2,0,29,21,1522.85,False,FIFA World Cup qualification,1,1.891892,0.648649,76.459459,1452.855405,3.000000,0.200000,99.200000,1503.612000
2935,2022-03-29,South Korea,United Arab Emirates,0,1,29,69,1522.85,False,FIFA World Cup qualification,0,1.894737,0.631579,75.000000,1454.697368,2.800000,0.200000,89.000000,1510.362000
3032,2022-06-02,South Korea,Brazil,1,5,29,1,1519.54,False,Friendly,1,1.846154,0.641026,74.846154,1456.444872,1.800000,0.200000,90.400000,1513.484000
3099,2022-06-06,South Korea,Chile,2,0,29,28,1519.54,False,Friendly,1,1.825000,0.750000,73.000000,1458.022250,1.200000,1.200000,54.400000,1515.944000
3167,2022-06-10,South Korea,Paraguay,2,2,29,50,1519.54,False,Friendly,1,1.829268,0.731707,71.902439,1459.522683,1.400000,1.200000,41.000000,1518.404000
3249,2022-06-14,South Korea,Egypt,4,1,29,32,1519.54,False,Friendly,1,1.833333,0.761905,71.380952,1460.951667,1.400000,1.600000,33.800000,1520.864000
3274,2022-07-24,South Korea,Hong Kong,3,0,28,145,1526.20,True,EAFF Championship,1,1.883721,0.767442,70.465116,1462.314186,1.800000,1.800000,36.000000,1520.202000
3275,2022-07-27,South Korea,Japan,0,3,28,24,1526.20,False,EAFF Championship,0,1.909091,0.750000,72.159091,1463.766136,2.400000,1.600000,51.200000,1520.872000
3310,2022-09-23,South Korea,Costa Rica,2,2,28,34,1526.02,False,Friendly,1,1.866667,0.800000,71.088889,1465.153556,2.200000,1.200000,55.800000,1522.204000
3383,2022-09-27,South Korea,Cameroon,1,0,28,38,1526.02,False,Friendly,1,1.869565,0.826087,70.282609,1466.476739,2.200000,1.600000,57.000000,1523.500000

In [24]:
len(_)

47

### Sanity Check

In [25]:
df_stats[ df_stats.team == "South Korea" ].loc[:, ["team", "opponent", "goals_scored", "goals_avg", "goals_avg_lastn"]].head(8)

            team      opponent  goals_scored  goals_avg  goals_avg_lastn
45   South Korea    Costa Rica             2        NaN              NaN
122  South Korea         Chile             0   2.000000         2.000000
169  South Korea       Uruguay             2   1.000000         1.000000
246  South Korea        Panama             2   1.333333         1.333333
332  South Korea     Australia             1   1.500000         1.500000
393  South Korea    Uzbekistan             4   1.400000         1.400000
430  South Korea  Saudi Arabia             0   1.833333         1.800000
438  South Korea   Philippines             1   1.571429         1.800000

#### Goal Scored

In [26]:
# all prior matches since Aug 2018
(2 + 0 + 2 + 2 + 1 + 4) / 6

1.8333333333333333

In [27]:
# most recent 5 matches
(0 + 2 + 2 + 1 + 4) / 5

1.8

In [28]:
# all prior matches since Aug 2018
(2 + 0 + 2 + 2 + 1 + 4 + 0) / 7

1.5714285714285714

In [29]:
# most recent 5 matches
(2 + 2 + 1 + 4 + 0) / 5

1.8

#### Opponent Rank

In [30]:
df_stats[ df_stats.team == "South Korea" ].loc[:, ["team", "opponent", "opp_rank", "rank_avg", "rank_avg_lastn"]].head(7)

            team      opponent  opp_rank   rank_avg  rank_avg_lastn
45   South Korea    Costa Rica        32        NaN             NaN
122  South Korea         Chile        12  32.000000       32.000000
169  South Korea       Uruguay         5  22.000000       22.000000
246  South Korea        Panama        70  16.333333       16.333333
332  South Korea     Australia        42  29.750000       29.750000
393  South Korea    Uzbekistan        94  32.200000       32.200000
430  South Korea  Saudi Arabia        69  42.500000       44.600000

In [31]:
# all prior matches since Aug 2018
(32 + 12 + 5 + 70 + 42 + 94) / 6

42.5

In [32]:
# most recent 5 matches
(12 + 5 + 70 + 42 + 94) / 5

44.6

In [33]:
df_stats.loc[1348]

,date,team,opponent,goals_scored,goals_conceded,team_rank,opp_rank,team_points,neutral,tournament,is_home,goals_avg,goals_suf_avg,rank_avg,points_avg,goals_avg_lastn,goals_suf_avg_lastn,rank_avg_lastn,points_avg_lastn
1348,2019-12-18,Japan,South Korea,0,1,28,41,1500.0,False,EAFF Championship,0,2.00,0.916667,70.333333,1454.208333,3.4,0.8,119.6,1491.8
1348,2019-12-18,South Korea,Japan,1,0,41,28,1459.0,False,EAFF Championship,1,1.65,0.650000,72.050000,1430.350000,2.4,0.6,113.4,1465.6

## Drop First Games

In [34]:
# drop first games because of no prior history
df_stats.dropna(inplace=True)

In [35]:
df_stats[ df_stats["team"] == "South Korea" ]

,date,team,opponent,goals_scored,goals_conceded,team_rank,opp_rank,team_points,neutral,tournament,is_home,goals_avg,goals_suf_avg,rank_avg,points_avg,goals_avg_lastn,goals_suf_avg_lastn,rank_avg_lastn,points_avg_lastn
122,2018-09-11,South Korea,Chile,0,0,57,12,1387.00,False,Friendly,1,2.000000,0.000000,32.000000,1387.000000,2.000000,0.000000,32.000000,1387.000000
169,2018-10-12,South Korea,Uruguay,2,1,55,5,1395.00,False,Friendly,1,1.000000,0.000000,22.000000,1387.000000,1.000000,0.000000,22.000000,1387.000000
246,2018-10-16,South Korea,Panama,2,2,55,70,1395.00,False,Friendly,1,1.333333,0.333333,16.333333,1389.666667,1.333333,0.333333,16.333333,1389.666667
332,2018-11-17,South Korea,Australia,1,1,53,42,1401.00,False,Friendly,0,1.500000,0.750000,29.750000,1391.000000,1.500000,0.750000,29.750000,1391.000000
393,2018-11-20,South Korea,Uzbekistan,4,0,53,94,1401.00,True,Friendly,1,1.400000,0.800000,32.200000,1393.000000,1.400000,0.800000,32.200000,1393.000000
430,2018-12-31,South Korea,Saudi Arabia,0,0,53,69,1405.00,True,Friendly,1,1.833333,0.666667,42.500000,1394.333333,1.800000,0.800000,44.600000,1395.800000
438,2019-01-07,South Korea,Philippines,1,0,53,116,1405.00,True,AFC Asian Cup,1,1.571429,0.571429,46.285714,1395.857143,1.800000,0.800000,56.000000,1399.400000
470,2019-01-22,South Korea,Bahrain,2,1,53,113,1405.00,True,AFC Asian Cup,1,1.500000,0.500000,55.000000,1397.000000,1.600000,0.600000,78.200000,1401.400000
473,2019-01-25,South Korea,Qatar,0,1,53,93,1405.00,True,AFC Asian Cup,1,1.555556,0.555556,61.444444,1397.888889,1.600000,0.400000,86.800000,1403.400000
509,2019-03-22,South Korea,Bolivia,1,0,38,60,1451.00,False,Friendly,1,1.400000,0.600000,64.600000,1398.600000,1.400000,0.400000,97.000000,1404.200000
585,2019-03-26,South Korea,Colombia,2,1,38,12,1451.00,False,Friendly,1,1.363636,0.545455,64.181818,1403.363636,0.800000,0.400000,90.200000,1414.200000
663,2019-06-07,South Korea,Australia,1,0,37,41,1462.00,False,Friendly,1,1.416667,0.583333,59.833333,1407.333333,1.200000,0.600000,78.800000,1423.400000
723,2019-06-11,South Korea,Iran,1,1,37,21,1462.00,False,Friendly,1,1.384615,0.538462,58.384615,1411.538462,1.200000,0.600000,63.800000,1434.800000
893,2019-09-05,South Korea,Georgia,2,2,37,94,1467.00,True,Friendly,1,1.357143,0.571429,55.714286,1415.142857,1.000000,0.600000,45.400000,1446.200000
1021,2019-09-10,South Korea,Turkmenistan,2,0,37,132,1467.00,False,FIFA World Cup qualification,0,1.400000,0.666667,58.266667,1418.600000,1.400000,0.800000,45.600000,1458.600000
1075,2019-10-10,South Korea,Sri Lanka,8,0,37,202,1470.00,False,FIFA World Cup qualification,1,1.437500,0.625000,62.875000,1421.625000,1.600000,0.800000,60.000000,1461.800000
1219,2019-11-14,South Korea,Lebanon,0,0,39,91,1466.00,False,FIFA World Cup qualification,0,1.823529,0.588235,71.058824,1424.470588,2.800000,0.600000,98.000000,1465.600000
1312,2019-11-19,South Korea,Brazil,0,3,39,3,1466.00,True,Friendly,0,1.722222,0.555556,72.166667,1426.777778,2.600000,0.600000,108.000000,1466.400000
1346,2019-12-11,South Korea,Hong Kong,2,0,41,139,1459.00,False,EAFF Championship,1,1.631579,0.684211,68.526316,1428.842105,2.400000,1.000000,104.400000,1467.200000
1348,2019-12-18,South Korea,Japan,1,0,41,28,1459.00,False,EAFF Championship,1,1.650000,0.650000,72.050000,1430.350000,2.400000,0.600000,113.400000,1465.600000
1597,2020-11-14,South Korea,Mexico,2,3,38,11,1464.00,True,Friendly,0,1.619048,0.619048,69.952381,1431.714286,2.200000,0.600000,92.600000,1464.000000
1647,2020-11-17,South Korea,Qatar,2,1,38,57,1464.00,True,Friendly,1,1.636364,0.727273,67.272727,1433.181818,1.000000,1.200000,54.400000,1462.800000
1728,2021-03-25,South Korea,Japan,0,3,38,27,1465.00,False,Friendly,0,1.652174,0.739130,66.826087,1434.521739,1.400000,1.400000,47.600000,1462.400000
1951,2021-06-05,South Korea,Turkmenistan,5,0,39,130,1460.25,False,FIFA World Cup qualification,1,1.583333,0.833333,65.166667,1435.791667,1.400000,1.400000,52.400000,1462.200000
2013,2021-06-09,South Korea,Sri Lanka,5,0,39,204,1460.25,False,FIFA World Cup qualification,1,1.720000,0.800000,67.760000,1436.770000,2.000000,1.400000,50.600000,1462.450000
2039,2021-06-13,South Korea,Lebanon,2,1,39,93,1460.25,False,FIFA World Cup qualification,1,1.846154,0.769231,73.000000,1437.673077,2.800000,1.400000,85.800000,1462.700000
2233,2021-09-02,South Korea,Iraq,0,0,36,70,1474.96,False,FIFA World Cup qualification,1,1.851852,0.777778,73.740741,1438.509259,2.800000,1.000000,102.200000,1461.950000
2326,2021-09-07,South Korea,Lebanon,1,0,36,98,1474.96,False,FIFA World Cup qualification,1,1.785714,0.750000,73.607143,1439.811071,2.400000,0.800000,104.800000,1464.142000
2380,2021-10-07,South Korea,Syria,2,1,36,81,1479.41,False,FIFA World Cup qualification,1,1.758621,0.724138,74.448276,1441.023103,2.600000,0.200000,119.000000,1466.134000
2477,2021-10-12,South Korea,Iran,1,1,36,22,1479.41,False,FIFA World Cup qualification,0,1.766667,0.733333,74.666667,1442.302667,2.000000,0.400000,109.200000,1469.966000
2537,2021-11-11,South Korea,United Arab Emirates,1,0,35,71,1489.10,False,FIFA World Cup qualification,1,1.741935,0.741935,72.967742,1443.499677,1.200000,0.600000,72.800000,1473.798000
2635,2021-11-16,South Korea,Iraq,3,0,35,72,1489.10,True,FIFA World Cup qualification,0,1.718750,0.718750,72.906250,1444.924687,1.000000,0.400000,68.400000,1479.568000
2745,2022-01-15,South Korea,Iceland,5,1,33,62,1507.24,True,Friendly,1,1.757576,0.696970,72.878788,1446.263333,1.600000,0.400000,68.800000,1482.396000
2761,2022-01-20,South Korea,Moldova,4,0,33,181,1507.24,True,Friendly,1,1.852941,0.705882,72.558824,1448.056765,2.400000,0.600000,61.600000,1488.852000
2781,2022-01-27,South Korea,Lebanon,1,0,33,95,1507.24,False,FIFA World Cup qualification,0,1.914286,0.685714,75.657143,1449.747714,2.800000,0.400000,81.600000,1494.418000
2811,2022-02-01,South Korea,Syria,2,0,33,86,1507.24,True,FIFA World Cup qualification,0,1.888889,0.666667,76.194444,1451.344722,2.800000,0.200000,96.200000,1499.984000
2851,2022-03-24,South Korea,Iran,2,0,29,21,1522.85,False,FIFA World Cup qualification,1,1.891892,0.648649,76.459459,1452.855405,3.000000,0.200000,99.200000,1503.612000
2935,2022-03-29,South Korea,United Arab Emirates,0,1,29,69,1522.85,False,FIFA World Cup qualification,0,1.894737,0.631579,75.000000,1454.697368,2.800000,0.200000,89.000000,1510.362000
3032,2022-06-02,South Korea,Brazil,1,5,29,1,1519.54,False,Friendly,1,1.846154,0.641026,74.846154,1456.444872,1.800000,0.200000,90.400000,1513.484000
3099,2022-06-06,South Korea,Chile,2,0,29,28,1519.54,False,Friendly,1,1.825000,0.750000,73.000000,1458.022250,1.200000,1.200000,54.400000,1515.944000
3167,2022-06-10,South Korea,Paraguay,2,2,29,50,1519.54,False,Friendly,1,1.829268,0.731707,71.902439,1459.522683,1.400000,1.200000,41.000000,1518.404000
3249,2022-06-14,South Korea,Egypt,4,1,29,32,1519.54,False,Friendly,1,1.833333,0.761905,71.380952,1460.951667,1.400000,1.600000,33.800000,1520.864000
3274,2022-07-24,South Korea,Hong Kong,3,0,28,145,1526.20,True,EAFF Championship,1,1.883721,0.767442,70.465116,1462.314186,1.800000,1.800000,36.000000,1520.202000
3275,2022-07-27,South Korea,Japan,0,3,28,24,1526.20,False,EAFF Championship,0,1.909091,0.750000,72.159091,1463.766136,2.400000,1.600000,51.200000,1520.872000
3310,2022-09-23,South Korea,Costa Rica,2,2,28,34,1526.02,False,Friendly,1,1.866667,0.800000,71.088889,1465.153556,2.200000,1.200000,55.800000,1522.204000
3383,2022-09-27,South Korea,Cameroon,1,0,28,38,1526.02,False,Friendly,1,1.869565,0.826087,70.282609,1466.476739,2.200000,1.600000,57.000000,1523.500000

In [36]:
len(_)

46

## Save

In [37]:
df_stats.to_parquet("./intermediate/stats.parquet")