**_Copyright Notice_**

This notebook is available for educational purposes. You may not use or distribute this notebook for commercial purposes. You may make copies of this notebook and use or distribute it for educational purposes as long as you cite the author as the source of the notebook.

Jaeyoung Chun | School of Applied Artificial Intelligence | Handong Global University

# Merge

In [1]:
import pandas as pd

## Load

In [2]:
df_stats = pd.read_parquet("./intermediate/stats.parquet")

In [3]:
df_stats

,date,team,opponent,goals_scored,goals_conceded,team_rank,opp_rank,team_points,neutral,tournament,is_home,goals_avg,goals_suf_avg,rank_avg,points_avg,goals_avg_lastn,goals_suf_avg_lastn,rank_avg_lastn,points_avg_lastn
3,2018-08-20,Jamaica,Barbados,2,2,54,160,1400.00,False,Friendly,0,5.000000,1.000000,168.000000,1400.000000,5.0,1.0,168.0,1400.000
4,2018-08-26,Cuba,Barbados,0,0,181,160,940.00,False,Friendly,0,0.000000,1.000000,146.000000,940.000000,0.0,1.0,146.0,940.000
4,2018-08-26,Barbados,Cuba,0,0,160,181,1005.00,False,Friendly,1,2.000000,2.000000,54.000000,1005.000000,2.0,2.0,54.0,1005.000
6,2018-08-29,Cuba,Barbados,2,0,181,160,940.00,False,Friendly,0,0.000000,0.500000,153.000000,940.000000,0.0,0.5,153.0,940.000
6,2018-08-29,Barbados,Cuba,0,2,160,181,1005.00,False,Friendly,1,1.000000,1.000000,117.500000,1005.000000,1.0,1.0,117.5,1005.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3404,2022-09-27,Kosovo,Cyprus,5,1,106,108,1183.90,False,UEFA Nations League,1,1.434783,1.304348,77.456522,1150.793913,1.2,1.4,65.4,1175.900
3405,2022-09-27,Northern Ireland,Greece,1,3,58,49,1399.10,False,UEFA Nations League,0,1.023256,1.279070,57.906977,1454.282093,1.2,1.4,95.6,1418.660
3405,2022-09-27,Greece,Northern Ireland,3,1,49,58,1441.45,False,UEFA Nations League,1,1.090909,0.909091,73.931818,1419.390682,1.4,0.2,96.2,1425.434
3406,2022-09-30,Fiji,Solomon Islands,1,0,163,137,993.37,True,MSG Prime Minister's Cup,1,1.666667,1.222222,156.166667,991.177222,1.2,1.2,157.4,994.530
3406,2022-09-30,Solomon Islands,Fiji,0,1,137,163,1092.56,True,MSG Prime Minister's Cup,0,2.785714,1.857143,163.642857,1077.445714,1.8,2.0,151.6,1080.692

In [4]:
# index refers to the same match (home vs. away = away vs. home)
df_stats.groupby(level=0).size()

3       1
4       2
6       2
9       1
10      1
       ..
3402    2
3403    2
3404    2
3405    2
3406    2
Length: 3335, dtype: int64

In [5]:
df_stats.loc[1348]

,date,team,opponent,goals_scored,goals_conceded,team_rank,opp_rank,team_points,neutral,tournament,is_home,goals_avg,goals_suf_avg,rank_avg,points_avg,goals_avg_lastn,goals_suf_avg_lastn,rank_avg_lastn,points_avg_lastn
1348,2019-12-18,Japan,South Korea,0,1,28,41,1500.0,False,EAFF Championship,0,2.00,0.916667,70.333333,1454.208333,3.4,0.8,119.6,1491.8
1348,2019-12-18,South Korea,Japan,1,0,41,28,1459.0,False,EAFF Championship,1,1.65,0.650000,72.050000,1430.350000,2.4,0.6,113.4,1465.6

In [6]:
basic_cols = ["date", "team", "opponent", "goals_scored"]

stat_cols = [
    'goals_avg', 'goals_avg_lastn',
    'goals_suf_avg', 'goals_suf_avg_lastn',
    'rank_avg', 'rank_avg_lastn',
    'points_avg', 'points_avg_lastn'
]

In [7]:
basic_cols + stat_cols

['date',
 'team',
 'opponent',
 'goals_scored',
 'goals_avg',
 'goals_avg_lastn',
 'goals_suf_avg',
 'goals_suf_avg_lastn',
 'rank_avg',
 'rank_avg_lastn',
 'points_avg',
 'points_avg_lastn']

## Home Team

In [8]:
df_stats[ df_stats.is_home == 1].loc[:, basic_cols + stat_cols]

,date,team,opponent,goals_scored,goals_avg,goals_avg_lastn,goals_suf_avg,goals_suf_avg_lastn,rank_avg,rank_avg_lastn,points_avg,points_avg_lastn
4,2018-08-26,Barbados,Cuba,0,2.000000,2.0,2.000000,2.0,54.000000,54.0,1005.000000,1005.000
6,2018-08-29,Barbados,Cuba,0,1.000000,1.0,1.000000,1.0,117.500000,117.5,1005.000000,1005.000
10,2018-09-04,Macau,Guam,2,1.000000,1.0,4.000000,4.0,164.500000,164.5,924.000000,924.000
12,2018-09-04,Bangladesh,Bhutan,2,0.000000,0.0,1.000000,1.0,200.000000,200.0,904.000000,904.000
31,2018-09-06,Mongolia,Guam,1,4.000000,4.0,1.000000,1.0,185.000000,185.0,920.000000,920.000
...,...,...,...,...,...,...,...,...,...,...,...,...
3402,2022-09-27,Norway,Serbia,0,1.761905,1.4,0.880952,1.0,63.547619,38.6,1444.219762,1468.514
3403,2022-09-27,Sweden,Slovenia,1,1.411765,1.2,1.137255,2.0,51.254902,39.4,1572.445294,1580.504
3404,2022-09-27,Kosovo,Cyprus,5,1.434783,1.2,1.304348,1.4,77.456522,65.4,1150.793913,1175.900
3405,2022-09-27,Greece,Northern Ireland,3,1.090909,1.4,0.909091,0.2,73.931818,96.2,1419.390682,1425.434
3406,2022-09-30,Fiji,Solomon Islands,1,1.666667,1.2,1.222222,1.2,156.166667,157.4,991.177222,994.530

In [9]:
df_home = df_stats[ df_stats.is_home == 1].loc[:, basic_cols + stat_cols].copy()

## Away Team

In [10]:
df_stats[ df_stats.is_home == 0].loc[:, basic_cols + stat_cols]

,date,team,opponent,goals_scored,goals_avg,goals_avg_lastn,goals_suf_avg,goals_suf_avg_lastn,rank_avg,rank_avg_lastn,points_avg,points_avg_lastn
3,2018-08-20,Jamaica,Barbados,2,5.000000,5.0,1.000000,1.0,168.000000,168.0,1400.000000,1400.000
4,2018-08-26,Cuba,Barbados,0,0.000000,0.0,1.000000,1.0,146.000000,146.0,940.000000,940.000
6,2018-08-29,Cuba,Barbados,2,0.000000,0.0,0.500000,0.5,153.000000,153.0,940.000000,940.000
9,2018-09-02,Macau,Mongolia,1,1.000000,1.0,4.000000,4.0,143.000000,143.0,924.000000,924.000
13,2018-09-05,Solomon Islands,Fiji,1,4.000000,4.0,1.000000,1.0,185.000000,185.0,1072.000000,1072.000
...,...,...,...,...,...,...,...,...,...,...,...,...
3402,2022-09-27,Serbia,Norway,2,1.800000,2.2,1.111111,1.0,54.533333,42.0,1498.653333,1547.930
3403,2022-09-27,Slovenia,Sweden,1,1.380952,1.0,1.000000,1.8,76.357143,29.2,1373.109286,1377.080
3404,2022-09-27,Cyprus,Kosovo,1,0.767442,0.6,1.767442,1.4,70.418605,63.8,1236.506512,1184.976
3405,2022-09-27,Northern Ireland,Greece,1,1.023256,1.2,1.279070,1.4,57.906977,95.6,1454.282093,1418.660
3406,2022-09-30,Solomon Islands,Fiji,0,2.785714,1.8,1.857143,2.0,163.642857,151.6,1077.445714,1080.692

In [11]:
df_away = df_stats[ df_stats.is_home == 0].loc[:, basic_cols + stat_cols].copy()

## Sanity Check

In [12]:
df_home.loc[1348]

date                   2019-12-18 00:00:00
team                           South Korea
opponent                             Japan
goals_scored                             1
goals_avg                             1.65
goals_avg_lastn                        2.4
goals_suf_avg                         0.65
goals_suf_avg_lastn                    0.6
rank_avg                             72.05
rank_avg_lastn                       113.4
points_avg                         1430.35
points_avg_lastn                    1465.6
Name: 1348, dtype: object

In [13]:
df_away.loc[1348]

date                   2019-12-18 00:00:00
team                                 Japan
opponent                       South Korea
goals_scored                             0
goals_avg                              2.0
goals_avg_lastn                        3.4
goals_suf_avg                     0.916667
goals_suf_avg_lastn                    0.8
rank_avg                         70.333333
rank_avg_lastn                       119.6
points_avg                     1454.208333
points_avg_lastn                    1491.8
Name: 1348, dtype: object

In [14]:
df_home_away = pd.merge(
    df_home, df_away,
    left_on=["date", "team", "opponent"],
    right_on=["date", "opponent", "team"],
    suffixes=["_home", "_away"],
    how="inner"
)

In [15]:
df_home_away

,date,team_home,opponent_home,goals_scored_home,goals_avg_home,goals_avg_lastn_home,goals_suf_avg_home,goals_suf_avg_lastn_home,rank_avg_home,rank_avg_lastn_home,...,opponent_away,goals_scored_away,goals_avg_away,goals_avg_lastn_away,goals_suf_avg_away,goals_suf_avg_lastn_away,rank_avg_away,rank_avg_lastn_away,points_avg_away,points_avg_lastn_away
0,2018-08-26,Barbados,Cuba,0,2.000000,2.0,2.000000,2.0,54.000000,54.0,...,Barbados,0,0.000000,0.0,1.000000,1.0,146.000000,146.0,940.000000,940.000
1,2018-08-29,Barbados,Cuba,0,1.000000,1.0,1.000000,1.0,117.500000,117.5,...,Barbados,2,0.000000,0.0,0.500000,0.5,153.000000,153.0,940.000000,940.000
2,2018-09-06,Mongolia,Guam,1,4.000000,4.0,1.000000,1.0,185.000000,185.0,...,Mongolia,1,0.000000,0.0,2.000000,2.0,185.000000,185.0,912.000000,912.000
3,2018-09-06,Nepal,Bhutan,4,1.000000,1.0,2.000000,2.0,201.000000,201.0,...,Nepal,0,0.000000,0.0,2.000000,2.0,194.000000,194.0,932.000000,932.000
4,2018-09-06,Bangladesh,Pakistan,1,1.000000,1.0,0.500000,0.5,191.500000,191.5,...,Bangladesh,0,2.000000,2.0,1.000000,1.0,161.000000,161.0,884.000000,884.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3275,2022-09-27,Norway,Serbia,0,1.761905,1.4,0.880952,1.0,63.547619,38.6,...,Norway,2,1.800000,2.2,1.111111,1.0,54.533333,42.0,1498.653333,1547.930
3276,2022-09-27,Sweden,Slovenia,1,1.411765,1.2,1.137255,2.0,51.254902,39.4,...,Sweden,1,1.380952,1.0,1.000000,1.8,76.357143,29.2,1373.109286,1377.080
3277,2022-09-27,Kosovo,Cyprus,5,1.434783,1.2,1.304348,1.4,77.456522,65.4,...,Kosovo,1,0.767442,0.6,1.767442,1.4,70.418605,63.8,1236.506512,1184.976
3278,2022-09-27,Greece,Northern Ireland,3,1.090909,1.4,0.909091,0.2,73.931818,96.2,...,Greece,1,1.023256,1.2,1.279070,1.4,57.906977,95.6,1454.282093,1418.660
3279,2022-09-30,Fiji,Solomon Islands,1,1.666667,1.2,1.222222,1.2,156.166667,157.4,...,Fiji,0,2.785714,1.8,1.857143,2.0,163.642857,151.6,1077.445714,1080.692

In [16]:
# rename
df_home_away.rename(
    columns={
        "team_home": "home_team",
        "opponent_home": "away_team"
    },
    inplace=True
)

In [17]:
# drop unnecessary
df_home_away.drop(
    columns=["team_away", "opponent_away"],
    inplace=True
)

In [18]:
df_home_away

,date,home_team,away_team,goals_scored_home,goals_avg_home,goals_avg_lastn_home,goals_suf_avg_home,goals_suf_avg_lastn_home,rank_avg_home,rank_avg_lastn_home,...,points_avg_lastn_home,goals_scored_away,goals_avg_away,goals_avg_lastn_away,goals_suf_avg_away,goals_suf_avg_lastn_away,rank_avg_away,rank_avg_lastn_away,points_avg_away,points_avg_lastn_away
0,2018-08-26,Barbados,Cuba,0,2.000000,2.0,2.000000,2.0,54.000000,54.0,...,1005.000,0,0.000000,0.0,1.000000,1.0,146.000000,146.0,940.000000,940.000
1,2018-08-29,Barbados,Cuba,0,1.000000,1.0,1.000000,1.0,117.500000,117.5,...,1005.000,2,0.000000,0.0,0.500000,0.5,153.000000,153.0,940.000000,940.000
2,2018-09-06,Mongolia,Guam,1,4.000000,4.0,1.000000,1.0,185.000000,185.0,...,920.000,1,0.000000,0.0,2.000000,2.0,185.000000,185.0,912.000000,912.000
3,2018-09-06,Nepal,Bhutan,4,1.000000,1.0,2.000000,2.0,201.000000,201.0,...,1004.000,0,0.000000,0.0,2.000000,2.0,194.000000,194.0,932.000000,932.000
4,2018-09-06,Bangladesh,Pakistan,1,1.000000,1.0,0.500000,0.5,191.500000,191.5,...,904.000,0,2.000000,2.0,1.000000,1.0,161.000000,161.0,884.000000,884.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3275,2022-09-27,Norway,Serbia,0,1.761905,1.4,0.880952,1.0,63.547619,38.6,...,1468.514,2,1.800000,2.2,1.111111,1.0,54.533333,42.0,1498.653333,1547.930
3276,2022-09-27,Sweden,Slovenia,1,1.411765,1.2,1.137255,2.0,51.254902,39.4,...,1580.504,1,1.380952,1.0,1.000000,1.8,76.357143,29.2,1373.109286,1377.080
3277,2022-09-27,Kosovo,Cyprus,5,1.434783,1.2,1.304348,1.4,77.456522,65.4,...,1175.900,1,0.767442,0.6,1.767442,1.4,70.418605,63.8,1236.506512,1184.976
3278,2022-09-27,Greece,Northern Ireland,3,1.090909,1.4,0.909091,0.2,73.931818,96.2,...,1425.434,1,1.023256,1.2,1.279070,1.4,57.906977,95.6,1454.282093,1418.660
3279,2022-09-30,Fiji,Solomon Islands,1,1.666667,1.2,1.222222,1.2,156.166667,157.4,...,994.530,0,2.785714,1.8,1.857143,2.0,163.642857,151.6,1077.445714,1080.692

In [19]:
df_home_away.loc[1224]

date                        2019-12-18 00:00:00
home_team                           South Korea
away_team                                 Japan
goals_scored_home                             1
goals_avg_home                             1.65
goals_avg_lastn_home                        2.4
goals_suf_avg_home                         0.65
goals_suf_avg_lastn_home                    0.6
rank_avg_home                             72.05
rank_avg_lastn_home                       113.4
points_avg_home                         1430.35
points_avg_lastn_home                    1465.6
goals_scored_away                             0
goals_avg_away                              2.0
goals_avg_lastn_away                        3.4
goals_suf_avg_away                     0.916667
goals_suf_avg_lastn_away                    0.8
rank_avg_away                         70.333333
rank_avg_lastn_away                       119.6
points_avg_away                     1454.208333
points_avg_lastn_away                    1491.8
Name: 1224, dtype: object

In [20]:
df_home_away.to_parquet("./intermediate/features.parquet")