**_Copyright Notice_**

This notebook is available for educational purposes. You may not use or distribute this notebook for commercial purposes. You may make copies of this notebook and use or distribute it for educational purposes as long as you cite the author as the source of the notebook.

Jaeyoung Chun | School of Applied Artificial Intelligence | Handong Global University

# Feature Engineering (Part 2)

In [1]:
import pandas as pd
import os

## Stats Difference

### Compute

In [2]:
df_features = pd.read_parquet("./intermediate/features.parquet")

In [3]:
df_features

,date,home_team,away_team,goals_scored_home,goals_avg_home,goals_avg_lastn_home,goals_suf_avg_home,goals_suf_avg_lastn_home,rank_avg_home,rank_avg_lastn_home,...,points_avg_lastn_home,goals_scored_away,goals_avg_away,goals_avg_lastn_away,goals_suf_avg_away,goals_suf_avg_lastn_away,rank_avg_away,rank_avg_lastn_away,points_avg_away,points_avg_lastn_away
0,2018-08-26,Barbados,Cuba,0,2.000000,2.0,2.000000,2.0,54.000000,54.0,...,1005.000,0,0.000000,0.0,1.000000,1.0,146.000000,146.0,940.000000,940.000
1,2018-08-29,Barbados,Cuba,0,1.000000,1.0,1.000000,1.0,117.500000,117.5,...,1005.000,2,0.000000,0.0,0.500000,0.5,153.000000,153.0,940.000000,940.000
2,2018-09-06,Mongolia,Guam,1,4.000000,4.0,1.000000,1.0,185.000000,185.0,...,920.000,1,0.000000,0.0,2.000000,2.0,185.000000,185.0,912.000000,912.000
3,2018-09-06,Nepal,Bhutan,4,1.000000,1.0,2.000000,2.0,201.000000,201.0,...,1004.000,0,0.000000,0.0,2.000000,2.0,194.000000,194.0,932.000000,932.000
4,2018-09-06,Bangladesh,Pakistan,1,1.000000,1.0,0.500000,0.5,191.500000,191.5,...,904.000,0,2.000000,2.0,1.000000,1.0,161.000000,161.0,884.000000,884.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3275,2022-09-27,Norway,Serbia,0,1.761905,1.4,0.880952,1.0,63.547619,38.6,...,1468.514,2,1.800000,2.2,1.111111,1.0,54.533333,42.0,1498.653333,1547.930
3276,2022-09-27,Sweden,Slovenia,1,1.411765,1.2,1.137255,2.0,51.254902,39.4,...,1580.504,1,1.380952,1.0,1.000000,1.8,76.357143,29.2,1373.109286,1377.080
3277,2022-09-27,Kosovo,Cyprus,5,1.434783,1.2,1.304348,1.4,77.456522,65.4,...,1175.900,1,0.767442,0.6,1.767442,1.4,70.418605,63.8,1236.506512,1184.976
3278,2022-09-27,Greece,Northern Ireland,3,1.090909,1.4,0.909091,0.2,73.931818,96.2,...,1425.434,1,1.023256,1.2,1.279070,1.4,57.906977,95.6,1454.282093,1418.660
3279,2022-09-30,Fiji,Solomon Islands,1,1.666667,1.2,1.222222,1.2,156.166667,157.4,...,994.530,0,2.785714,1.8,1.857143,2.0,163.642857,151.6,1077.445714,1080.692

In [4]:
stat_cols = [
    'goals_avg', 'goals_avg_lastn',
    'goals_suf_avg', 'goals_suf_avg_lastn',
    'rank_avg', 'rank_avg_lastn',
    'points_avg', 'points_avg_lastn'
]

In [5]:
df_features["goals_avg_home"]  - df_features["goals_avg_away"]

0       2.000000
1       1.000000
2       4.000000
3       1.000000
4      -1.000000
          ...
3275   -0.038095
3276    0.030812
3277    0.667341
3278    0.067653
3279   -1.119048
Length: 3280, dtype: float64

In [6]:
for stat_col in stat_cols:
    col_home = f"{stat_col}_home"  # goals_avg_home
    col_away = f"{stat_col}_away"  # goals_avg_away
    col_diff = f"{stat_col}_diff"  # goals_avg_diff
    df_features[col_diff] = df_features[col_home]  - df_features[col_away]

In [7]:
df_features

,date,home_team,away_team,goals_scored_home,goals_avg_home,goals_avg_lastn_home,goals_suf_avg_home,goals_suf_avg_lastn_home,rank_avg_home,rank_avg_lastn_home,...,points_avg_away,points_avg_lastn_away,goals_avg_diff,goals_avg_lastn_diff,goals_suf_avg_diff,goals_suf_avg_lastn_diff,rank_avg_diff,rank_avg_lastn_diff,points_avg_diff,points_avg_lastn_diff
0,2018-08-26,Barbados,Cuba,0,2.000000,2.0,2.000000,2.0,54.000000,54.0,...,940.000000,940.000,2.000000,2.0,1.000000,1.0,-92.000000,-92.0,65.000000,65.000
1,2018-08-29,Barbados,Cuba,0,1.000000,1.0,1.000000,1.0,117.500000,117.5,...,940.000000,940.000,1.000000,1.0,0.500000,0.5,-35.500000,-35.5,65.000000,65.000
2,2018-09-06,Mongolia,Guam,1,4.000000,4.0,1.000000,1.0,185.000000,185.0,...,912.000000,912.000,4.000000,4.0,-1.000000,-1.0,0.000000,0.0,8.000000,8.000
3,2018-09-06,Nepal,Bhutan,4,1.000000,1.0,2.000000,2.0,201.000000,201.0,...,932.000000,932.000,1.000000,1.0,0.000000,0.0,7.000000,7.0,72.000000,72.000
4,2018-09-06,Bangladesh,Pakistan,1,1.000000,1.0,0.500000,0.5,191.500000,191.5,...,884.000000,884.000,-1.000000,-1.0,-0.500000,-0.5,30.500000,30.5,20.000000,20.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3275,2022-09-27,Norway,Serbia,0,1.761905,1.4,0.880952,1.0,63.547619,38.6,...,1498.653333,1547.930,-0.038095,-0.8,-0.230159,0.0,9.014286,-3.4,-54.433571,-79.416
3276,2022-09-27,Sweden,Slovenia,1,1.411765,1.2,1.137255,2.0,51.254902,39.4,...,1373.109286,1377.080,0.030812,0.2,0.137255,0.2,-25.102241,10.2,199.336008,203.424
3277,2022-09-27,Kosovo,Cyprus,5,1.434783,1.2,1.304348,1.4,77.456522,65.4,...,1236.506512,1184.976,0.667341,0.6,-0.463094,0.0,7.037917,1.6,-85.712599,-9.076
3278,2022-09-27,Greece,Northern Ireland,3,1.090909,1.4,0.909091,0.2,73.931818,96.2,...,1454.282093,1418.660,0.067653,0.2,-0.369979,-1.2,16.024841,0.6,-34.891411,6.774
3279,2022-09-30,Fiji,Solomon Islands,1,1.666667,1.2,1.222222,1.2,156.166667,157.4,...,1077.445714,1080.692,-1.119048,-0.6,-0.634921,-0.8,-7.476190,5.8,-86.268492,-86.162

### Sanity Check

In [8]:
df_features.loc[1224]

date                        2019-12-18 00:00:00
home_team                           South Korea
away_team                                 Japan
goals_scored_home                             1
goals_avg_home                             1.65
goals_avg_lastn_home                        2.4
goals_suf_avg_home                         0.65
goals_suf_avg_lastn_home                    0.6
rank_avg_home                             72.05
rank_avg_lastn_home                       113.4
points_avg_home                         1430.35
points_avg_lastn_home                    1465.6
goals_scored_away                             0
goals_avg_away                              2.0
goals_avg_lastn_away                        3.4
goals_suf_avg_away                     0.916667
goals_suf_avg_lastn_away                    0.8
rank_avg_away                         70.333333
rank_avg_lastn_away                       119.6
points_avg_away                     1454.208333
points_avg_lastn_away                    1491.8
goals_avg_diff                            -0.35
goals_avg_lastn_diff                       -1.0
goals_suf_avg_diff                    -0.266667
goals_suf_avg_lastn_diff                   -0.2
rank_avg_diff                          1.716667
rank_avg_lastn_diff                        -6.2
points_avg_diff                      -23.858333
points_avg_lastn_diff                     -26.2
Name: 1224, dtype: object

```
rank_avg_home                         72.05
rank_avg_away                     70.333333
--------------------------------------------
rank_avg_diff                      1.716667
```

In [9]:
72.05 - 70.333333

1.716667000000001

## Rank Difference

### Compute

In [10]:
df_match_rank = pd.read_parquet(
    "./intermediate/match_rank.parquet",
    columns=[
        "date",
        "home_team", "away_team",
        "home_score", "away_score",
        "rank_home", "rank_away"
    ]
)

In [11]:
df_match_rank

,date,home_team,away_team,home_score,away_score,rank_home,rank_away
0,2018-08-18,Andorra,United Arab Emirates,0,0,130,77
1,2018-08-18,Grenada,Jamaica,1,5,168,54
2,2018-08-18,Guatemala,Cuba,1,0,146,181
3,2018-08-20,Barbados,Jamaica,2,2,160,54
4,2018-08-26,Barbados,Cuba,0,0,160,181
...,...,...,...,...,...,...,...
3402,2022-09-27,Norway,Serbia,0,2,36,25
3403,2022-09-27,Sweden,Slovenia,1,1,20,65
3404,2022-09-27,Kosovo,Cyprus,5,1,106,108
3405,2022-09-27,Greece,Northern Ireland,3,1,49,58
3406,2022-09-30,Fiji,Solomon Islands,1,0,163,137

In [12]:
df_match_rank["rank_diff"] = df_match_rank["rank_home"] - df_match_rank["rank_away"]

In [13]:
df_match_rank

,date,home_team,away_team,home_score,away_score,rank_home,rank_away,rank_diff
0,2018-08-18,Andorra,United Arab Emirates,0,0,130,77,53
1,2018-08-18,Grenada,Jamaica,1,5,168,54,114
2,2018-08-18,Guatemala,Cuba,1,0,146,181,-35
3,2018-08-20,Barbados,Jamaica,2,2,160,54,106
4,2018-08-26,Barbados,Cuba,0,0,160,181,-21
...,...,...,...,...,...,...,...,...
3402,2022-09-27,Norway,Serbia,0,2,36,25,11
3403,2022-09-27,Sweden,Slovenia,1,1,20,65,-45
3404,2022-09-27,Kosovo,Cyprus,5,1,106,108,-2
3405,2022-09-27,Greece,Northern Ireland,3,1,49,58,-9
3406,2022-09-30,Fiji,Solomon Islands,1,0,163,137,26

### Sanity Check

In [14]:
df_match_rank.loc[1348]

date          2019-12-18 00:00:00
home_team             South Korea
away_team                   Japan
home_score                      1
away_score                      0
rank_home                      41
rank_away                      28
rank_diff                      13
Name: 1348, dtype: object

In [15]:
41 - 28

13

## Merge Stats Difference and Rank Difference

In [16]:
df_final = pd.merge(
    df_features,
    df_match_rank,
    on=["date", "home_team", "away_team"],
    how="left"
)

In [17]:
df_final

,date,home_team,away_team,goals_scored_home,goals_avg_home,goals_avg_lastn_home,goals_suf_avg_home,goals_suf_avg_lastn_home,rank_avg_home,rank_avg_lastn_home,...,goals_suf_avg_lastn_diff,rank_avg_diff,rank_avg_lastn_diff,points_avg_diff,points_avg_lastn_diff,home_score,away_score,rank_home,rank_away,rank_diff
0,2018-08-26,Barbados,Cuba,0,2.000000,2.0,2.000000,2.0,54.000000,54.0,...,1.0,-92.000000,-92.0,65.000000,65.000,0,0,160,181,-21
1,2018-08-29,Barbados,Cuba,0,1.000000,1.0,1.000000,1.0,117.500000,117.5,...,0.5,-35.500000,-35.5,65.000000,65.000,0,2,160,181,-21
2,2018-09-06,Mongolia,Guam,1,4.000000,4.0,1.000000,1.0,185.000000,185.0,...,-1.0,0.000000,0.0,8.000000,8.000,1,1,186,190,-4
3,2018-09-06,Nepal,Bhutan,4,1.000000,1.0,2.000000,2.0,201.000000,201.0,...,0.0,7.000000,7.0,72.000000,72.000,4,0,161,183,-22
4,2018-09-06,Bangladesh,Pakistan,1,1.000000,1.0,0.500000,0.5,191.500000,191.5,...,-0.5,30.500000,30.5,20.000000,20.000,1,0,194,201,-7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3275,2022-09-27,Norway,Serbia,0,1.761905,1.4,0.880952,1.0,63.547619,38.6,...,0.0,9.014286,-3.4,-54.433571,-79.416,0,2,36,25,11
3276,2022-09-27,Sweden,Slovenia,1,1.411765,1.2,1.137255,2.0,51.254902,39.4,...,0.2,-25.102241,10.2,199.336008,203.424,1,1,20,65,-45
3277,2022-09-27,Kosovo,Cyprus,5,1.434783,1.2,1.304348,1.4,77.456522,65.4,...,0.0,7.037917,1.6,-85.712599,-9.076,5,1,106,108,-2
3278,2022-09-27,Greece,Northern Ireland,3,1.090909,1.4,0.909091,0.2,73.931818,96.2,...,-1.2,16.024841,0.6,-34.891411,6.774,3,1,49,58,-9
3279,2022-09-30,Fiji,Solomon Islands,1,1.666667,1.2,1.222222,1.2,156.166667,157.4,...,-0.8,-7.476190,5.8,-86.268492,-86.162,1,0,163,137,26

In [18]:
df_final.loc[1224]

date                        2019-12-18 00:00:00
home_team                           South Korea
away_team                                 Japan
goals_scored_home                             1
goals_avg_home                             1.65
goals_avg_lastn_home                        2.4
goals_suf_avg_home                         0.65
goals_suf_avg_lastn_home                    0.6
rank_avg_home                             72.05
rank_avg_lastn_home                       113.4
points_avg_home                         1430.35
points_avg_lastn_home                    1465.6
goals_scored_away                             0
goals_avg_away                              2.0
goals_avg_lastn_away                        3.4
goals_suf_avg_away                     0.916667
goals_suf_avg_lastn_away                    0.8
rank_avg_away                         70.333333
rank_avg_lastn_away                       119.6
points_avg_away                     1454.208333
points_avg_lastn_away                    1491.8
goals_avg_diff                            -0.35
goals_avg_lastn_diff                       -1.0
goals_suf_avg_diff                    -0.266667
goals_suf_avg_lastn_diff                   -0.2
rank_avg_diff                          1.716667
rank_avg_lastn_diff                        -6.2
points_avg_diff                      -23.858333
points_avg_lastn_diff                     -26.2
home_score                                    1
away_score                                    0
rank_home                                    41
rank_away                                    28
rank_diff                                    13
Name: 1224, dtype: object

In [19]:
df_final[ df_final.home_team == "South Korea" ]

,date,home_team,away_team,goals_scored_home,goals_avg_home,goals_avg_lastn_home,goals_suf_avg_home,goals_suf_avg_lastn_home,rank_avg_home,rank_avg_lastn_home,...,goals_suf_avg_lastn_diff,rank_avg_diff,rank_avg_lastn_diff,points_avg_diff,points_avg_lastn_diff,home_score,away_score,rank_home,rank_away,rank_diff
74,2018-10-12,South Korea,Uruguay,2,1.000000,1.000000,0.000000,0.000000,22.000000,22.000000,...,-1.000000,6.000000,6.000000,-240.000000,-240.000000,2,1,55,5,50
143,2018-10-16,South Korea,Panama,2,1.333333,1.333333,0.333333,0.333333,16.333333,16.333333,...,-2.166667,-26.166667,-26.166667,48.666667,48.666667,2,2,55,70,-15
284,2018-11-20,South Korea,Uzbekistan,4,1.400000,1.400000,0.800000,0.800000,32.200000,32.200000,...,0.300000,-38.050000,-38.050000,144.750000,144.750000,4,0,53,94,-41
318,2018-12-31,South Korea,Saudi Arabia,0,1.833333,1.800000,0.666667,0.800000,42.500000,44.600000,...,-0.400000,-36.300000,-34.200000,58.733333,60.200000,0,0,53,69,-16
326,2019-01-07,South Korea,Philippines,1,1.571429,1.800000,0.571429,0.800000,46.285714,56.000000,...,-1.000000,-79.825397,-60.200000,223.523810,226.400000,1,0,53,116,-63
358,2019-01-22,South Korea,Bahrain,2,1.500000,1.600000,0.500000,0.600000,55.000000,78.200000,...,0.200000,-45.666667,-20.800000,217.666667,223.400000,2,1,53,113,-60
361,2019-01-25,South Korea,Qatar,0,1.555556,1.600000,0.555556,0.400000,61.444444,86.800000,...,-0.200000,-5.828283,20.000000,145.707071,145.400000,0,1,53,93,-40
397,2019-03-22,South Korea,Bolivia,1,1.400000,1.400000,0.600000,0.400000,64.600000,97.000000,...,-0.400000,-25.233333,3.200000,21.933333,27.800000,1,0,38,60,-22
473,2019-03-26,South Korea,Colombia,2,1.363636,0.800000,0.545455,0.400000,64.181818,90.200000,...,-0.400000,38.581818,64.600000,-163.636364,-152.800000,2,1,38,12,26
549,2019-06-07,South Korea,Australia,1,1.416667,1.200000,0.583333,0.600000,59.833333,78.800000,...,-0.200000,-32.611111,-12.400000,-27.222222,-12.600000,1,0,37,41,-4
609,2019-06-11,South Korea,Iran,1,1.384615,1.200000,0.538462,0.600000,58.384615,63.800000,...,0.000000,-25.365385,-16.800000,-70.461538,-53.200000,1,1,37,21,16
773,2019-09-05,South Korea,Georgia,2,1.357143,1.000000,0.571429,0.600000,55.714286,45.400000,...,-1.200000,-44.385714,-27.400000,157.942857,183.200000,2,2,37,94,-57
952,2019-10-10,South Korea,Sri Lanka,8,1.437500,1.600000,0.625000,0.800000,62.875000,60.000000,...,-2.000000,-91.670455,-84.200000,535.988636,578.600000,8,0,37,202,-165
1222,2019-12-11,South Korea,Hong Kong,2,1.631579,2.400000,0.684211,1.000000,68.526316,104.400000,...,0.000000,-58.598684,-4.600000,358.717105,399.600000,2,0,41,139,-98
1224,2019-12-18,South Korea,Japan,1,1.650000,2.400000,0.650000,0.600000,72.050000,113.400000,...,-0.200000,1.716667,-6.200000,-23.858333,-26.200000,1,0,41,28,13
1522,2020-11-17,South Korea,Qatar,2,1.636364,1.000000,0.727273,1.200000,67.272727,54.400000,...,-0.600000,-8.327273,-21.200000,106.781818,66.600000,2,1,38,57,-19
1825,2021-06-05,South Korea,Turkmenistan,5,1.583333,1.400000,0.833333,1.400000,65.166667,52.400000,...,0.400000,-49.133333,-85.600000,333.491667,371.400000,5,0,39,130,-91
1887,2021-06-09,South Korea,Sri Lanka,5,1.720000,2.000000,0.800000,1.400000,67.760000,50.600000,...,-3.000000,-69.373333,-52.400000,556.565333,595.836000,5,0,39,204,-165
1913,2021-06-13,South Korea,Lebanon,2,1.846154,2.800000,0.769231,1.400000,73.000000,85.800000,...,-0.600000,-36.857143,-49.400000,158.236886,201.268000,2,1,39,93,-54
2107,2021-09-02,South Korea,Iraq,0,1.851852,2.800000,0.777778,1.000000,73.740741,102.200000,...,0.200000,-24.687831,-26.000000,121.649259,109.130000,0,0,36,70,-34
2200,2021-09-07,South Korea,Lebanon,1,1.785714,2.400000,0.750000,0.800000,73.607143,104.800000,...,-0.600000,-34.601190,-20.000000,164.048571,211.682000,1,0,36,98,-62
2254,2021-10-07,South Korea,Syria,2,1.758621,2.600000,0.724138,0.200000,74.448276,119.000000,...,-0.800000,-28.586207,23.800000,141.135517,160.786000,2,1,36,81,-45
2411,2021-11-11,South Korea,United Arab Emirates,1,1.741935,1.200000,0.741935,0.600000,72.967742,72.800000,...,-0.600000,-31.874363,0.000000,110.523888,119.710000,1,0,35,71,-36
2619,2022-01-15,South Korea,Iceland,5,1.757576,1.600000,0.696970,0.400000,72.878788,68.800000,...,-0.600000,16.902597,-26.000000,1.543333,87.430000,5,1,33,62,-29
2635,2022-01-20,South Korea,Moldova,4,1.852941,2.400000,0.705882,0.600000,72.558824,61.600000,...,-2.400000,2.789593,12.400000,488.919842,553.538000,4,0,33,181,-148
2724,2022-03-24,South Korea,Iran,2,1.891892,3.000000,0.648649,0.200000,76.459459,99.200000,...,-0.200000,-11.071791,27.800000,-52.379595,-45.044000,2,0,29,21,8
2905,2022-06-02,South Korea,Brazil,1,1.846154,1.800000,0.641026,0.200000,74.846154,90.400000,...,0.000000,41.954849,51.000000,-274.351650,-310.496000,1,5,29,1,28
2972,2022-06-06,South Korea,Chile,2,1.825000,1.200000,0.750000,1.200000,73.000000,54.400000,...,-0.800000,39.818182,20.600000,-103.295932,-26.954000,2,0,29,28,1
3040,2022-06-10,South Korea,Paraguay,2,1.829268,1.400000,0.731707,1.200000,71.902439,41.000000,...,-1.200000,36.543465,19.400000,-8.900394,71.724000,2,2,29,50,-21
3122,2022-06-14,South Korea,Egypt,4,1.833333,1.400000,0.761905,1.600000,71.380952,33.800000,...,1.000000,-18.944048,-21.400000,27.428167,31.422000,4,1,29,32,-3
3147,2022-07-24,South Korea,Hong Kong,3,1.883721,1.800000,0.767442,1.800000,70.465116,36.000000,...,-0.800000,-34.423773,-85.000000,395.552519,465.260000,3,0,28,145,-117
3183,2022-09-23,South Korea,Costa Rica,2,1.866667,2.200000,0.800000,1.200000,71.088889,55.800000,...,0.600000,15.762802,0.200000,17.538338,42.532000,2,2,28,34,-6
3256,2022-09-27,South Korea,Cameroon,1,1.869565,2.200000,0.826087,1.600000,70.282609,57.000000,...,0.200000,-19.774534,-15.400000,44.857025,50.616000,1,0,28,38,-10

In [20]:
df_final.to_parquet("./intermediate/final.parquet")